# -*- coding: utf-8 -*-
#
# Copyright (C) 2015 Stefan Gansinger
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

"""
Languages codes according to ISO639/2.
Source: http://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt
"""

from PyQt5.QtCore import QCoreApplication

ISO639_2_CODES = {
    'aar':QCoreApplication.translate('ISO639_2','Afar'),
    'abk':QCoreApplication.translate('ISO639_2','Abkhazian'),
    'ace':QCoreApplication.translate('ISO639_2','Achinese'),
    'ach':QCoreApplication.translate('ISO639_2','Acoli'),
    'ada':QCoreApplication.translate('ISO639_2','Adangme'),
    'ady':QCoreApplication.translate('ISO639_2','Adyghe; Adygei'),
    'afa':QCoreApplication.translate('ISO639_2','Afro-Asiatic languages'),
    'afh':QCoreApplication.translate('ISO639_2','Afrihili'),
    'afr':QCoreApplication.translate('ISO639_2','Afrikaans'),
    'ain':QCoreApplication.translate('ISO639_2','Ainu'),
    'aka':QCoreApplication.translate('ISO639_2','Akan'),
    'akk':QCoreApplication.translate('ISO639_2','Akkadian'),
    'alb':QCoreApplication.translate('ISO639_2','Albanian'),
    'ale':QCoreApplication.translate('ISO639_2','Aleut'),
    'alg':QCoreApplication.translate('ISO639_2','Algonquian languages'),
    'alt':QCoreApplication.translate('ISO639_2','Southern Altai'),
    'amh':QCoreApplication.translate('ISO639_2','Amharic'),
    'ang':QCoreApplication.translate('ISO639_2','English, Old (ca.450-1100)'),
    'anp':QCoreApplication.translate('ISO639_2','Angika'),
    'apa':QCoreApplication.translate('ISO639_2','Apache languages'),
    'ara':QCoreApplication.translate('ISO639_2','Arabic'),
    'arc':QCoreApplication.translate('ISO639_2','Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)'),
    'arg':QCoreApplication.translate('ISO639_2','Aragonese'),
    'arm':QCoreApplication.translate('ISO639_2','Armenian'),
    'arn':QCoreApplication.translate('ISO639_2','Mapudungun; Mapuche'),
    'arp':QCoreApplication.translate('ISO639_2','Arapaho'),
    'art':QCoreApplication.translate('ISO639_2','Artificial languages'),
    'arw':QCoreApplication.translate('ISO639_2','Arawak'),
    'asm':QCoreApplication.translate('ISO639_2','Assamese'),
    'ast':QCoreApplication.translate('ISO639_2','Asturian; Bable; Leonese; Asturleonese'),
    'ath':QCoreApplication.translate('ISO639_2','Athapascan languages'),
    'aus':QCoreApplication.translate('ISO639_2','Australian languages'),
    'ava':QCoreApplication.translate('ISO639_2','Avaric'),
    'ave':QCoreApplication.translate('ISO639_2','Avestan'),
    'awa':QCoreApplication.translate('ISO639_2','Awadhi'),
    'aym':QCoreApplication.translate('ISO639_2','Aymara'),
    'aze':QCoreApplication.translate('ISO639_2','Azerbaijani'),
    'bad':QCoreApplication.translate('ISO639_2','Banda languages'),
    'bai':QCoreApplication.translate('ISO639_2','Bamileke languages'),
    'bak':QCoreApplication.translate('ISO639_2','Bashkir'),
    'bal':QCoreApplication.translate('ISO639_2','Baluchi'),
    'bam':QCoreApplication.translate('ISO639_2','Bambara'),
    'ban':QCoreApplication.translate('ISO639_2','Balinese'),
    'baq':QCoreApplication.translate('ISO639_2','Basque'),
    'bas':QCoreApplication.translate('ISO639_2','Basa'),
    'bat':QCoreApplication.translate('ISO639_2','Baltic languages'),
    'bej':QCoreApplication.translate('ISO639_2','Beja; Bedawiyet'),
    'bel':QCoreApplication.translate('ISO639_2','Belarusian'),
    'bem':QCoreApplication.translate('ISO639_2','Bemba'),
    'ben':QCoreApplication.translate('ISO639_2','Bengali'),
    'ber':QCoreApplication.translate('ISO639_2','Berber languages'),
    'bho':QCoreApplication.translate('ISO639_2','Bhojpuri'),
    'bih':QCoreApplication.translate('ISO639_2','Bihari languages'),
    'bik':QCoreApplication.translate('ISO639_2','Bikol'),
    'bin':QCoreApplication.translate('ISO639_2','Bini; Edo'),
    'bis':QCoreApplication.translate('ISO639_2','Bislama'),
    'bla':QCoreApplication.translate('ISO639_2','Siksika'),
    'bnt':QCoreApplication.translate('ISO639_2','Bantu (Other)'),
    'bos':QCoreApplication.translate('ISO639_2','Bosnian'),
    'bra':QCoreApplication.translate('ISO639_2','Braj'),
    'bre':QCoreApplication.translate('ISO639_2','Breton'),
    'btk':QCoreApplication.translate('ISO639_2','Batak languages'),
    'bua':QCoreApplication.translate('ISO639_2','Buriat'),
    'bug':QCoreApplication.translate('ISO639_2','Buginese'),
    'bul':QCoreApplication.translate('ISO639_2','Bulgarian'),
    'bur':QCoreApplication.translate('ISO639_2','Burmese'),
    'byn':QCoreApplication.translate('ISO639_2','Blin; Bilin'),
    'cad':QCoreApplication.translate('ISO639_2','Caddo'),
    'cai':QCoreApplication.translate('ISO639_2','Central American Indian languages'),
    'car':QCoreApplication.translate('ISO639_2','Galibi Carib'),
    'cat':QCoreApplication.translate('ISO639_2','Catalan; Valencian'),
    'cau':QCoreApplication.translate('ISO639_2','Caucasian languages'),
    'ceb':QCoreApplication.translate('ISO639_2','Cebuano'),
    'cel':QCoreApplication.translate('ISO639_2','Celtic languages'),
    'cha':QCoreApplication.translate('ISO639_2','Chamorro'),
    'chb':QCoreApplication.translate('ISO639_2','Chibcha'),
    'che':QCoreApplication.translate('ISO639_2','Chechen'),
    'chg':QCoreApplication.translate('ISO639_2','Chagatai'),
    'chi':QCoreApplication.translate('ISO639_2','Chinese'),
    'chk':QCoreApplication.translate('ISO639_2','Chuukese'),
    'chm':QCoreApplication.translate('ISO639_2','Mari'),
    'chn':QCoreApplication.translate('ISO639_2','Chinook jargon'),
    'cho':QCoreApplication.translate('ISO639_2','Choctaw'),
    'chp':QCoreApplication.translate('ISO639_2','Chipewyan; Dene Suline'),
    'chr':QCoreApplication.translate('ISO639_2','Cherokee'),
    'chu':QCoreApplication.translate('ISO639_2','Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
    'chv':QCoreApplication.translate('ISO639_2','Chuvash'),
    'chy':QCoreApplication.translate('ISO639_2','Cheyenne'),
    'cmc':QCoreApplication.translate('ISO639_2','Chamic languages'),
    'cop':QCoreApplication.translate('ISO639_2','Coptic'),
    'cor':QCoreApplication.translate('ISO639_2','Cornish'),
    'cos':QCoreApplication.translate('ISO639_2','Corsican'),
    'cpe':QCoreApplication.translate('ISO639_2','Creoles and pidgins, English based'),
    'cpf':QCoreApplication.translate('ISO639_2','Creoles and pidgins, French-based '),
    'cpp':QCoreApplication.translate('ISO639_2','Creoles and pidgins, Portuguese-based '),
    'cre':QCoreApplication.translate('ISO639_2','Cree'),
    'crh':QCoreApplication.translate('ISO639_2','Crimean Tatar; Crimean Turkish'),
    'crp':QCoreApplication.translate('ISO639_2','Creoles and pidgins '),
    'csb':QCoreApplication.translate('ISO639_2','Kashubian'),
    'cus':QCoreApplication.translate('ISO639_2','Cushitic languages'),
    'cze':QCoreApplication.translate('ISO639_2','Czech'),
    'dak':QCoreApplication.translate('ISO639_2','Dakota'),
    'dan':QCoreApplication.translate('ISO639_2','Danish'),
    'dar':QCoreApplication.translate('ISO639_2','Dargwa'),
    'day':QCoreApplication.translate('ISO639_2','Land Dayak languages'),
    'del':QCoreApplication.translate('ISO639_2','Delaware'),
    'den':QCoreApplication.translate('ISO639_2','Slave (Athapascan)'),
    'dgr':QCoreApplication.translate('ISO639_2','Dogrib'),
    'din':QCoreApplication.translate('ISO639_2','Dinka'),
    'div':QCoreApplication.translate('ISO639_2','Divehi; Dhivehi; Maldivian'),
    'doi':QCoreApplication.translate('ISO639_2','Dogri'),
    'dra':QCoreApplication.translate('ISO639_2','Dravidian languages'),
    'dsb':QCoreApplication.translate('ISO639_2','Lower Sorbian'),
    'dua':QCoreApplication.translate('ISO639_2','Duala'),
    'dum':QCoreApplication.translate('ISO639_2','Dutch, Middle (ca.1050-1350)'),
    'dut':QCoreApplication.translate('ISO639_2','Dutch; Flemish'),
    'dyu':QCoreApplication.translate('ISO639_2','Dyula'),
    'dzo':QCoreApplication.translate('ISO639_2','Dzongkha'),
    'efi':QCoreApplication.translate('ISO639_2','Efik'),
    'egy':QCoreApplication.translate('ISO639_2','Egyptian (Ancient)'),
    'eka':QCoreApplication.translate('ISO639_2','Ekajuk'),
    'elx':QCoreApplication.translate('ISO639_2','Elamite'),
    'eng':QCoreApplication.translate('ISO639_2','English'),
    'enm':QCoreApplication.translate('ISO639_2','English, Middle (1100-1500)'),
    'epo':QCoreApplication.translate('ISO639_2','Esperanto'),
    'est':QCoreApplication.translate('ISO639_2','Estonian'),
    'ewe':QCoreApplication.translate('ISO639_2','Ewe'),
    'ewo':QCoreApplication.translate('ISO639_2','Ewondo'),
    'fan':QCoreApplication.translate('ISO639_2','Fang'),
    'fao':QCoreApplication.translate('ISO639_2','Faroese'),
    'fat':QCoreApplication.translate('ISO639_2','Fanti'),
    'fij':QCoreApplication.translate('ISO639_2','Fijian'),
    'fil':QCoreApplication.translate('ISO639_2','Filipino; Pilipino'),
    'fin':QCoreApplication.translate('ISO639_2','Finnish'),
    'fiu':QCoreApplication.translate('ISO639_2','Finno-Ugrian languages'),
    'fon':QCoreApplication.translate('ISO639_2','Fon'),
    'fre':QCoreApplication.translate('ISO639_2','French'),
    'frm':QCoreApplication.translate('ISO639_2','French, Middle (ca.1400-1600)'),
    'fro':QCoreApplication.translate('ISO639_2','French, Old (842-ca.1400)'),
    'frr':QCoreApplication.translate('ISO639_2','Northern Frisian'),
    'frs':QCoreApplication.translate('ISO639_2','Eastern Frisian'),
    'fry':QCoreApplication.translate('ISO639_2','Western Frisian'),
    'ful':QCoreApplication.translate('ISO639_2','Fulah'),
    'fur':QCoreApplication.translate('ISO639_2','Friulian'),
    'gaa':QCoreApplication.translate('ISO639_2','Ga'),
    'gay':QCoreApplication.translate('ISO639_2','Gayo'),
    'gba':QCoreApplication.translate('ISO639_2','Gbaya'),
    'gem':QCoreApplication.translate('ISO639_2','Germanic languages'),
    'geo':QCoreApplication.translate('ISO639_2','Georgian'),
    'ger':QCoreApplication.translate('ISO639_2','German'),
    'gez':QCoreApplication.translate('ISO639_2','Geez'),
    'gil':QCoreApplication.translate('ISO639_2','Gilbertese'),
    'gla':QCoreApplication.translate('ISO639_2','Gaelic; Scottish Gaelic'),
    'gle':QCoreApplication.translate('ISO639_2','Irish'),
    'glg':QCoreApplication.translate('ISO639_2','Galician'),
    'glv':QCoreApplication.translate('ISO639_2','Manx'),
    'gmh':QCoreApplication.translate('ISO639_2','German, Middle High (ca.1050-1500)'),
    'goh':QCoreApplication.translate('ISO639_2','German, Old High (ca.750-1050)'),
    'gon':QCoreApplication.translate('ISO639_2','Gondi'),
    'gor':QCoreApplication.translate('ISO639_2','Gorontalo'),
    'got':QCoreApplication.translate('ISO639_2','Gothic'),
    'grb':QCoreApplication.translate('ISO639_2','Grebo'),
    'grc':QCoreApplication.translate('ISO639_2','Greek, Ancient (to 1453)'),
    'gre':QCoreApplication.translate('ISO639_2','Greek, Modern (1453-)'),
    'grn':QCoreApplication.translate('ISO639_2','Guarani'),
    'gsw':QCoreApplication.translate('ISO639_2','Swiss German; Alemannic; Alsatian'),
    'guj':QCoreApplication.translate('ISO639_2','Gujarati'),
    'gwi':QCoreApplication.translate('ISO639_2','Gwich\'in'),
    'hai':QCoreApplication.translate('ISO639_2','Haida'),
    'hat':QCoreApplication.translate('ISO639_2','Haitian; Haitian Creole'),
    'hau':QCoreApplication.translate('ISO639_2','Hausa'),
    'haw':QCoreApplication.translate('ISO639_2','Hawaiian'),
    'heb':QCoreApplication.translate('ISO639_2','Hebrew'),
    'her':QCoreApplication.translate('ISO639_2','Herero'),
    'hil':QCoreApplication.translate('ISO639_2','Hiligaynon'),
    'him':QCoreApplication.translate('ISO639_2','Himachali languages; Western Pahari languages'),
    'hin':QCoreApplication.translate('ISO639_2','Hindi'),
    'hit':QCoreApplication.translate('ISO639_2','Hittite'),
    'hmn':QCoreApplication.translate('ISO639_2','Hmong; Mong'),
    'hmo':QCoreApplication.translate('ISO639_2','Hiri Motu'),
    'hrv':QCoreApplication.translate('ISO639_2','Croatian'),
    'hsb':QCoreApplication.translate('ISO639_2','Upper Sorbian'),
    'hun':QCoreApplication.translate('ISO639_2','Hungarian'),
    'hup':QCoreApplication.translate('ISO639_2','Hupa'),
    'iba':QCoreApplication.translate('ISO639_2','Iban'),
    'ibo':QCoreApplication.translate('ISO639_2','Igbo'),
    'ice':QCoreApplication.translate('ISO639_2','Icelandic'),
    'ido':QCoreApplication.translate('ISO639_2','Ido'),
    'iii':QCoreApplication.translate('ISO639_2','Sichuan Yi; Nuosu'),
    'ijo':QCoreApplication.translate('ISO639_2','Ijo languages'),
    'iku':QCoreApplication.translate('ISO639_2','Inuktitut'),
    'ile':QCoreApplication.translate('ISO639_2','Interlingue; Occidental'),
    'ilo':QCoreApplication.translate('ISO639_2','Iloko'),
    'ina':QCoreApplication.translate('ISO639_2','Interlingua (International Auxiliary Language Association)'),
    'inc':QCoreApplication.translate('ISO639_2','Indic languages'),
    'ind':QCoreApplication.translate('ISO639_2','Indonesian'),
    'ine':QCoreApplication.translate('ISO639_2','Indo-European languages'),
    'inh':QCoreApplication.translate('ISO639_2','Ingush'),
    'ipk':QCoreApplication.translate('ISO639_2','Inupiaq'),
    'ira':QCoreApplication.translate('ISO639_2','Iranian languages'),
    'iro':QCoreApplication.translate('ISO639_2','Iroquoian languages'),
    'ita':QCoreApplication.translate('ISO639_2','Italian'),
    'jav':QCoreApplication.translate('ISO639_2','Javanese'),
    'jbo':QCoreApplication.translate('ISO639_2','Lojban'),
    'jpn':QCoreApplication.translate('ISO639_2','Japanese'),
    'jpr':QCoreApplication.translate('ISO639_2','Judeo-Persian'),
    'jrb':QCoreApplication.translate('ISO639_2','Judeo-Arabic'),
    'kaa':QCoreApplication.translate('ISO639_2','Kara-Kalpak'),
    'kab':QCoreApplication.translate('ISO639_2','Kabyle'),
    'kac':QCoreApplication.translate('ISO639_2','Kachin; Jingpho'),
    'kal':QCoreApplication.translate('ISO639_2','Kalaallisut; Greenlandic'),
    'kam':QCoreApplication.translate('ISO639_2','Kamba'),
    'kan':QCoreApplication.translate('ISO639_2','Kannada'),
    'kar':QCoreApplication.translate('ISO639_2','Karen languages'),
    'kas':QCoreApplication.translate('ISO639_2','Kashmiri'),
    'kau':QCoreApplication.translate('ISO639_2','Kanuri'),
    'kaw':QCoreApplication.translate('ISO639_2','Kawi'),
    'kaz':QCoreApplication.translate('ISO639_2','Kazakh'),
    'kbd':QCoreApplication.translate('ISO639_2','Kabardian'),
    'kha':QCoreApplication.translate('ISO639_2','Khasi'),
    'khi':QCoreApplication.translate('ISO639_2','Khoisan languages'),
    'khm':QCoreApplication.translate('ISO639_2','Central Khmer'),
    'kho':QCoreApplication.translate('ISO639_2','Khotanese; Sakan'),
    'kik':QCoreApplication.translate('ISO639_2','Kikuyu; Gikuyu'),
    'kin':QCoreApplication.translate('ISO639_2','Kinyarwanda'),
    'kir':QCoreApplication.translate('ISO639_2','Kirghiz; Kyrgyz'),
    'kmb':QCoreApplication.translate('ISO639_2','Kimbundu'),
    'kok':QCoreApplication.translate('ISO639_2','Konkani'),
    'kom':QCoreApplication.translate('ISO639_2','Komi'),
    'kon':QCoreApplication.translate('ISO639_2','Kongo'),
    'kor':QCoreApplication.translate('ISO639_2','Korean'),
    'kos':QCoreApplication.translate('ISO639_2','Kosraean'),
    'kpe':QCoreApplication.translate('ISO639_2','Kpelle'),
    'krc':QCoreApplication.translate('ISO639_2','Karachay-Balkar'),
    'krl':QCoreApplication.translate('ISO639_2','Karelian'),
    'kro':QCoreApplication.translate('ISO639_2','Kru languages'),
    'kru':QCoreApplication.translate('ISO639_2','Kurukh'),
    'kua':QCoreApplication.translate('ISO639_2','Kuanyama; Kwanyama'),
    'kum':QCoreApplication.translate('ISO639_2','Kumyk'),
    'kur':QCoreApplication.translate('ISO639_2','Kurdish'),
    'kut':QCoreApplication.translate('ISO639_2','Kutenai'),
    'lad':QCoreApplication.translate('ISO639_2','Ladino'),
    'lah':QCoreApplication.translate('ISO639_2','Lahnda'),
    'lam':QCoreApplication.translate('ISO639_2','Lamba'),
    'lao':QCoreApplication.translate('ISO639_2','Lao'),
    'lat':QCoreApplication.translate('ISO639_2','Latin'),
    'lav':QCoreApplication.translate('ISO639_2','Latvian'),
    'lez':QCoreApplication.translate('ISO639_2','Lezghian'),
    'lim':QCoreApplication.translate('ISO639_2','Limburgan; Limburger; Limburgish'),
    'lin':QCoreApplication.translate('ISO639_2','Lingala'),
    'lit':QCoreApplication.translate('ISO639_2','Lithuanian'),
    'lol':QCoreApplication.translate('ISO639_2','Mongo'),
    'loz':QCoreApplication.translate('ISO639_2','Lozi'),
    'ltz':QCoreApplication.translate('ISO639_2','Luxembourgish; Letzeburgesch'),
    'lua':QCoreApplication.translate('ISO639_2','Luba-Lulua'),
    'lub':QCoreApplication.translate('ISO639_2','Luba-Katanga'),
    'lug':QCoreApplication.translate('ISO639_2','Ganda'),
    'lui':QCoreApplication.translate('ISO639_2','Luiseno'),
    'lun':QCoreApplication.translate('ISO639_2','Lunda'),
    'luo':QCoreApplication.translate('ISO639_2','Luo (Kenya and Tanzania)'),
    'lus':QCoreApplication.translate('ISO639_2','Lushai'),
    'mac':QCoreApplication.translate('ISO639_2','Macedonian'),
    'mad':QCoreApplication.translate('ISO639_2','Madurese'),
    'mag':QCoreApplication.translate('ISO639_2','Magahi'),
    'mah':QCoreApplication.translate('ISO639_2','Marshallese'),
    'mai':QCoreApplication.translate('ISO639_2','Maithili'),
    'mak':QCoreApplication.translate('ISO639_2','Makasar'),
    'mal':QCoreApplication.translate('ISO639_2','Malayalam'),
    'man':QCoreApplication.translate('ISO639_2','Mandingo'),
    'mao':QCoreApplication.translate('ISO639_2','Maori'),
    'map':QCoreApplication.translate('ISO639_2','Austronesian languages'),
    'mar':QCoreApplication.translate('ISO639_2','Marathi'),
    'mas':QCoreApplication.translate('ISO639_2','Masai'),
    'may':QCoreApplication.translate('ISO639_2','Malay'),
    'mdf':QCoreApplication.translate('ISO639_2','Moksha'),
    'mdr':QCoreApplication.translate('ISO639_2','Mandar'),
    'men':QCoreApplication.translate('ISO639_2','Mende'),
    'mga':QCoreApplication.translate('ISO639_2','Irish, Middle (900-1200)'),
    'mic':QCoreApplication.translate('ISO639_2','Mi\'kmaq; Micmac'),
    'min':QCoreApplication.translate('ISO639_2','Minangkabau'),
    'mis':QCoreApplication.translate('ISO639_2','Uncoded languages'),
    'mkh':QCoreApplication.translate('ISO639_2','Mon-Khmer languages'),
    'mlg':QCoreApplication.translate('ISO639_2','Malagasy'),
    'mlt':QCoreApplication.translate('ISO639_2','Maltese'),
    'mnc':QCoreApplication.translate('ISO639_2','Manchu'),
    'mni':QCoreApplication.translate('ISO639_2','Manipuri'),
    'mno':QCoreApplication.translate('ISO639_2','Manobo languages'),
    'moh':QCoreApplication.translate('ISO639_2','Mohawk'),
    'mon':QCoreApplication.translate('ISO639_2','Mongolian'),
    'mos':QCoreApplication.translate('ISO639_2','Mossi'),
    'mul':QCoreApplication.translate('ISO639_2','Multiple languages'),
    'mun':QCoreApplication.translate('ISO639_2','Munda languages'),
    'mus':QCoreApplication.translate('ISO639_2','Creek'),
    'mwl':QCoreApplication.translate('ISO639_2','Mirandese'),
    'mwr':QCoreApplication.translate('ISO639_2','Marwari'),
    'myn':QCoreApplication.translate('ISO639_2','Mayan languages'),
    'myv':QCoreApplication.translate('ISO639_2','Erzya'),
    'nah':QCoreApplication.translate('ISO639_2','Nahuatl languages'),
    'nai':QCoreApplication.translate('ISO639_2','North American Indian languages'),
    'nap':QCoreApplication.translate('ISO639_2','Neapolitan'),
    'nau':QCoreApplication.translate('ISO639_2','Nauru'),
    'nav':QCoreApplication.translate('ISO639_2','Navajo; Navaho'),
    'nbl':QCoreApplication.translate('ISO639_2','Ndebele, South; South Ndebele'),
    'nde':QCoreApplication.translate('ISO639_2','Ndebele, North; North Ndebele'),
    'ndo':QCoreApplication.translate('ISO639_2','Ndonga'),
    'nds':QCoreApplication.translate('ISO639_2','Low German; Low Saxon; German, Low; Saxon, Low'),
    'nep':QCoreApplication.translate('ISO639_2','Nepali'),
    'new':QCoreApplication.translate('ISO639_2','Nepal Bhasa; Newari'),
    'nia':QCoreApplication.translate('ISO639_2','Nias'),
    'nic':QCoreApplication.translate('ISO639_2','Niger-Kordofanian languages'),
    'niu':QCoreApplication.translate('ISO639_2','Niuean'),
    'nno':QCoreApplication.translate('ISO639_2','Norwegian Nynorsk; Nynorsk, Norwegian'),
    'nob':QCoreApplication.translate('ISO639_2','Bokmål, Norwegian; Norwegian Bokmål'),
    'nog':QCoreApplication.translate('ISO639_2','Nogai'),
    'non':QCoreApplication.translate('ISO639_2','Norse, Old'),
    'nor':QCoreApplication.translate('ISO639_2','Norwegian'),
    'nqo':QCoreApplication.translate('ISO639_2','N\'Ko'),
    'nso':QCoreApplication.translate('ISO639_2','Pedi; Sepedi; Northern Sotho'),
    'nub':QCoreApplication.translate('ISO639_2','Nubian languages'),
    'nwc':QCoreApplication.translate('ISO639_2','Classical Newari; Old Newari; Classical Nepal Bhasa'),
    'nya':QCoreApplication.translate('ISO639_2','Chichewa; Chewa; Nyanja'),
    'nym':QCoreApplication.translate('ISO639_2','Nyamwezi'),
    'nyn':QCoreApplication.translate('ISO639_2','Nyankole'),
    'nyo':QCoreApplication.translate('ISO639_2','Nyoro'),
    'nzi':QCoreApplication.translate('ISO639_2','Nzima'),
    'oci':QCoreApplication.translate('ISO639_2','Occitan (post 1500); Provençal'),
    'oji':QCoreApplication.translate('ISO639_2','Ojibwa'),
    'ori':QCoreApplication.translate('ISO639_2','Oriya'),
    'orm':QCoreApplication.translate('ISO639_2','Oromo'),
    'osa':QCoreApplication.translate('ISO639_2','Osage'),
    'oss':QCoreApplication.translate('ISO639_2','Ossetian; Ossetic'),
    'ota':QCoreApplication.translate('ISO639_2','Turkish, Ottoman (1500-1928)'),
    'oto':QCoreApplication.translate('ISO639_2','Otomian languages'),
    'paa':QCoreApplication.translate('ISO639_2','Papuan languages'),
    'pag':QCoreApplication.translate('ISO639_2','Pangasinan'),
    'pal':QCoreApplication.translate('ISO639_2','Pahlavi'),
    'pam':QCoreApplication.translate('ISO639_2','Pampanga; Kapampangan'),
    'pan':QCoreApplication.translate('ISO639_2','Panjabi; Punjabi'),
    'pap':QCoreApplication.translate('ISO639_2','Papiamento'),
    'pau':QCoreApplication.translate('ISO639_2','Palauan'),
    'peo':QCoreApplication.translate('ISO639_2','Persian, Old (ca.600-400 B.C.)'),
    'per':QCoreApplication.translate('ISO639_2','Persian'),
    'phi':QCoreApplication.translate('ISO639_2','Philippine languages'),
    'phn':QCoreApplication.translate('ISO639_2','Phoenician'),
    'pli':QCoreApplication.translate('ISO639_2','Pali'),
    'pol':QCoreApplication.translate('ISO639_2','Polish'),
    'pon':QCoreApplication.translate('ISO639_2','Pohnpeian'),
    'por':QCoreApplication.translate('ISO639_2','Portuguese'),
    'pra':QCoreApplication.translate('ISO639_2','Prakrit languages'),
    'pro':QCoreApplication.translate('ISO639_2','Provençal, Old (to 1500)'),
    'pus':QCoreApplication.translate('ISO639_2','Pushto; Pashto'),
    #'qaa-qtz':QCoreApplication.translate('ISO639_2','Reserved for local use'),
    'que':QCoreApplication.translate('ISO639_2','Quechua'),
    'raj':QCoreApplication.translate('ISO639_2','Rajasthani'),
    'rap':QCoreApplication.translate('ISO639_2','Rapanui'),
    'rar':QCoreApplication.translate('ISO639_2','Rarotongan; Cook Islands Maori'),
    'roa':QCoreApplication.translate('ISO639_2','Romance languages'),
    'roh':QCoreApplication.translate('ISO639_2','Romansh'),
    'rom':QCoreApplication.translate('ISO639_2','Romany'),
    'rum':QCoreApplication.translate('ISO639_2','Romanian; Moldavian; Moldovan'),
    'run':QCoreApplication.translate('ISO639_2','Rundi'),
    'rup':QCoreApplication.translate('ISO639_2','Aromanian; Arumanian; Macedo-Romanian'),
    'rus':QCoreApplication.translate('ISO639_2','Russian'),
    'sad':QCoreApplication.translate('ISO639_2','Sandawe'),
    'sag':QCoreApplication.translate('ISO639_2','Sango'),
    'sah':QCoreApplication.translate('ISO639_2','Yakut'),
    'sai':QCoreApplication.translate('ISO639_2','South American Indian (Other)'),
    'sal':QCoreApplication.translate('ISO639_2','Salishan languages'),
    'sam':QCoreApplication.translate('ISO639_2','Samaritan Aramaic'),
    'san':QCoreApplication.translate('ISO639_2','Sanskrit'),
    'sas':QCoreApplication.translate('ISO639_2','Sasak'),
    'sat':QCoreApplication.translate('ISO639_2','Santali'),
    'scn':QCoreApplication.translate('ISO639_2','Sicilian'),
    'sco':QCoreApplication.translate('ISO639_2','Scots'),
    'sel':QCoreApplication.translate('ISO639_2','Selkup'),
    'sem':QCoreApplication.translate('ISO639_2','Semitic languages'),
    'sga':QCoreApplication.translate('ISO639_2','Irish, Old (to 900)'),
    'sgn':QCoreApplication.translate('ISO639_2','Sign Languages'),
    'shn':QCoreApplication.translate('ISO639_2','Shan'),
    'sid':QCoreApplication.translate('ISO639_2','Sidamo'),
    'sin':QCoreApplication.translate('ISO639_2','Sinhala; Sinhalese'),
    'sio':QCoreApplication.translate('ISO639_2','Siouan languages'),
    'sit':QCoreApplication.translate('ISO639_2','Sino-Tibetan languages'),
    'sla':QCoreApplication.translate('ISO639_2','Slavic languages'),
    'slo':QCoreApplication.translate('ISO639_2','Slovak'),
    'slv':QCoreApplication.translate('ISO639_2','Slovenian'),
    'sma':QCoreApplication.translate('ISO639_2','Southern Sami'),
    'sme':QCoreApplication.translate('ISO639_2','Northern Sami'),
    'smi':QCoreApplication.translate('ISO639_2','Sami languages'),
    'smj':QCoreApplication.translate('ISO639_2','Lule Sami'),
    'smn':QCoreApplication.translate('ISO639_2','Inari Sami'),
    'smo':QCoreApplication.translate('ISO639_2','Samoan'),
    'sms':QCoreApplication.translate('ISO639_2','Skolt Sami'),
    'sna':QCoreApplication.translate('ISO639_2','Shona'),
    'snd':QCoreApplication.translate('ISO639_2','Sindhi'),
    'snk':QCoreApplication.translate('ISO639_2','Soninke'),
    'sog':QCoreApplication.translate('ISO639_2','Sogdian'),
    'som':QCoreApplication.translate('ISO639_2','Somali'),
    'son':QCoreApplication.translate('ISO639_2','Songhai languages'),
    'sot':QCoreApplication.translate('ISO639_2','Sotho, Southern'),
    'spa':QCoreApplication.translate('ISO639_2','Spanish; Castilian'),
    'srd':QCoreApplication.translate('ISO639_2','Sardinian'),
    'srn':QCoreApplication.translate('ISO639_2','Sranan Tongo'),
    'srp':QCoreApplication.translate('ISO639_2','Serbian'),
    'srr':QCoreApplication.translate('ISO639_2','Serer'),
    'ssa':QCoreApplication.translate('ISO639_2','Nilo-Saharan languages'),
    'ssw':QCoreApplication.translate('ISO639_2','Swati'),
    'suk':QCoreApplication.translate('ISO639_2','Sukuma'),
    'sun':QCoreApplication.translate('ISO639_2','Sundanese'),
    'sus':QCoreApplication.translate('ISO639_2','Susu'),
    'sux':QCoreApplication.translate('ISO639_2','Sumerian'),
    'swa':QCoreApplication.translate('ISO639_2','Swahili'),
    'swe':QCoreApplication.translate('ISO639_2','Swedish'),
    'syc':QCoreApplication.translate('ISO639_2','Classical Syriac'),
    'syr':QCoreApplication.translate('ISO639_2','Syriac'),
    'tah':QCoreApplication.translate('ISO639_2','Tahitian'),
    'tai':QCoreApplication.translate('ISO639_2','Tai languages'),
    'tam':QCoreApplication.translate('ISO639_2','Tamil'),
    'tat':QCoreApplication.translate('ISO639_2','Tatar'),
    'tel':QCoreApplication.translate('ISO639_2','Telugu'),
    'tem':QCoreApplication.translate('ISO639_2','Timne'),
    'ter':QCoreApplication.translate('ISO639_2','Tereno'),
    'tet':QCoreApplication.translate('ISO639_2','Tetum'),
    'tgk':QCoreApplication.translate('ISO639_2','Tajik'),
    'tgl':QCoreApplication.translate('ISO639_2','Tagalog'),
    'tha':QCoreApplication.translate('ISO639_2','Thai'),
    'tib':QCoreApplication.translate('ISO639_2','Tibetan'),
    'tig':QCoreApplication.translate('ISO639_2','Tigre'),
    'tir':QCoreApplication.translate('ISO639_2','Tigrinya'),
    'tiv':QCoreApplication.translate('ISO639_2','Tiv'),
    'tkl':QCoreApplication.translate('ISO639_2','Tokelau'),
    'tlh':QCoreApplication.translate('ISO639_2','Klingon; tlhIngan-Hol'),
    'tli':QCoreApplication.translate('ISO639_2','Tlingit'),
    'tmh':QCoreApplication.translate('ISO639_2','Tamashek'),
    'tog':QCoreApplication.translate('ISO639_2','Tonga (Nyasa)'),
    'ton':QCoreApplication.translate('ISO639_2','Tonga (Tonga Islands)'),
    'tpi':QCoreApplication.translate('ISO639_2','Tok Pisin'),
    'tsi':QCoreApplication.translate('ISO639_2','Tsimshian'),
    'tsn':QCoreApplication.translate('ISO639_2','Tswana'),
    'tso':QCoreApplication.translate('ISO639_2','Tsonga'),
    'tuk':QCoreApplication.translate('ISO639_2','Turkmen'),
    'tum':QCoreApplication.translate('ISO639_2','Tumbuka'),
    'tup':QCoreApplication.translate('ISO639_2','Tupi languages'),
    'tur':QCoreApplication.translate('ISO639_2','Turkish'),
    'tut':QCoreApplication.translate('ISO639_2','Altaic languages'),
    'tvl':QCoreApplication.translate('ISO639_2','Tuvalu'),
    'twi':QCoreApplication.translate('ISO639_2','Twi'),
    'tyv':QCoreApplication.translate('ISO639_2','Tuvinian'),
    'udm':QCoreApplication.translate('ISO639_2','Udmurt'),
    'uga':QCoreApplication.translate('ISO639_2','Ugaritic'),
    'uig':QCoreApplication.translate('ISO639_2','Uighur; Uyghur'),
    'ukr':QCoreApplication.translate('ISO639_2','Ukrainian'),
    'umb':QCoreApplication.translate('ISO639_2','Umbundu'),
    'und':QCoreApplication.translate('ISO639_2','Undetermined'),
    'urd':QCoreApplication.translate('ISO639_2','Urdu'),
    'uzb':QCoreApplication.translate('ISO639_2','Uzbek'),
    'vai':QCoreApplication.translate('ISO639_2','Vai'),
    'ven':QCoreApplication.translate('ISO639_2','Venda'),
    'vie':QCoreApplication.translate('ISO639_2','Vietnamese'),
    'vol':QCoreApplication.translate('ISO639_2','Volapük'),
    'vot':QCoreApplication.translate('ISO639_2','Votic'),
    'wak':QCoreApplication.translate('ISO639_2','Wakashan languages'),
    'wal':QCoreApplication.translate('ISO639_2','Walamo'),
    'war':QCoreApplication.translate('ISO639_2','Waray'),
    'was':QCoreApplication.translate('ISO639_2','Washo'),
    'wel':QCoreApplication.translate('ISO639_2','Welsh'),
    'wen':QCoreApplication.translate('ISO639_2','Sorbian languages'),
    'wln':QCoreApplication.translate('ISO639_2','Walloon'),
    'wol':QCoreApplication.translate('ISO639_2','Wolof'),
    'xal':QCoreApplication.translate('ISO639_2','Kalmyk; Oirat'),
    'xho':QCoreApplication.translate('ISO639_2','Xhosa'),
    'yao':QCoreApplication.translate('ISO639_2','Yao'),
    'yap':QCoreApplication.translate('ISO639_2','Yapese'),
    'yid':QCoreApplication.translate('ISO639_2','Yiddish'),
    'yor':QCoreApplication.translate('ISO639_2','Yoruba'),
    'ypk':QCoreApplication.translate('ISO639_2','Yupik languages'),
    'zap':QCoreApplication.translate('ISO639_2','Zapotec'),
    'zbl':QCoreApplication.translate('ISO639_2','Blissymbols; Blissymbolics; Bliss'),
    'zen':QCoreApplication.translate('ISO639_2','Zenaga'),
    'zgh':QCoreApplication.translate('ISO639_2','Standard Moroccan Tamazight'),
    'zha':QCoreApplication.translate('ISO639_2','Zhuang; Chuang'),
    'znd':QCoreApplication.translate('ISO639_2','Zande languages'),
    'zul':QCoreApplication.translate('ISO639_2','Zulu'),
    'zun':QCoreApplication.translate('ISO639_2','Zuni'),
    'zxx':QCoreApplication.translate('ISO639_2','No linguistic content; Not applicable'),
    'zza':QCoreApplication.translate('ISO639_2','Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'),
    'sqi':QCoreApplication.translate('ISO639_2','Albanian'),
    'hye':QCoreApplication.translate('ISO639_2','Armenian'),
    'eus':QCoreApplication.translate('ISO639_2','Basque'),
    'mya':QCoreApplication.translate('ISO639_2','Burmese'),
    'zho':QCoreApplication.translate('ISO639_2','Chinese'),
    'ces':QCoreApplication.translate('ISO639_2','Czech'),
    'nld':QCoreApplication.translate('ISO639_2','Dutch; Flemish'),
    'fra':QCoreApplication.translate('ISO639_2','French'),
    'kat':QCoreApplication.translate('ISO639_2','Georgian'),
    'deu':QCoreApplication.translate('ISO639_2','German'),
    'ell':QCoreApplication.translate('ISO639_2','Greek, Modern (1453-)'),
    'isl':QCoreApplication.translate('ISO639_2','Icelandic'),
    'mkd':QCoreApplication.translate('ISO639_2','Macedonian'),
    'mri':QCoreApplication.translate('ISO639_2','Maori'),
    'msa':QCoreApplication.translate('ISO639_2','Malay'),
    'fas':QCoreApplication.translate('ISO639_2','Persian'),
    'ron':QCoreApplication.translate('ISO639_2','Romanian; Moldavian; Moldovan'),
    'slk':QCoreApplication.translate('ISO639_2','Slovak'),
    'bod':QCoreApplication.translate('ISO639_2','Tibetan'),
    'cym':QCoreApplication.translate('ISO639_2','Welsh') }
